/*
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.consult;

//model

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.adyen.model.consult.Amount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * Discount
 */
@JsonPropertyOrder({
  Discount.JSON_PROPERTY_DISCOUNT_TAG,
  Discount.JSON_PROPERTY_DISCOUNT_NAME,
  Discount.JSON_PROPERTY_ESTIMATE_SAVINGS_AMOUNT
})
//pojo

public class Discount {
  public static final String JSON_PROPERTY_DISCOUNT_TAG = "discountTag";
  private String discountTag;

  public static final String JSON_PROPERTY_DISCOUNT_NAME = "discountName";
  private String discountName;

  public static final String JSON_PROPERTY_ESTIMATE_SAVINGS_AMOUNT = "estimateSavingsAmount";
  private Amount estimateSavingsAmount;

  public Discount() { 
  }

  /**
   * The discount tag is displayed as a superscript next to the discount name.
   *
   * @param discountTag
   * @return the current {@code Discount} instance, allowing for method chaining
   */
  public Discount discountTag(String discountTag) {
    this.discountTag = discountTag;
    return this;
  }

  /**
   * The discount tag is displayed as a superscript next to the discount name.
   * @return discountTag
   */
  @ApiModelProperty(value = "The discount tag is displayed as a superscript next to the discount name.")
  @JsonProperty(JSON_PROPERTY_DISCOUNT_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDiscountTag() {
    return discountTag;
  }

  /**
   * The discount tag is displayed as a superscript next to the discount name.
   *
   * @param discountTag
   */ 
  @JsonProperty(JSON_PROPERTY_DISCOUNT_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountTag(String discountTag) {
    this.discountTag = discountTag;
  }

  /**
   * The discount name displayed in the default language.
   *
   * @param discountName
   * @return the current {@code Discount} instance, allowing for method chaining
   */
  public Discount discountName(String discountName) {
    this.discountName = discountName;
    return this;
  }

  /**
   * The discount name displayed in the default language.
   * @return discountName
   */
  @ApiModelProperty(value = "The discount name displayed in the default language.")
  @JsonProperty(JSON_PROPERTY_DISCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDiscountName() {
    return discountName;
  }

  /**
   * The discount name displayed in the default language.
   *
   * @param discountName
   */ 
  @JsonProperty(JSON_PROPERTY_DISCOUNT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountName(String discountName) {
    this.discountName = discountName;
  }

  /**
   * estimateSavingsAmount
   *
   * @param estimateSavingsAmount
   * @return the current {@code Discount} instance, allowing for method chaining
   */
  public Discount estimateSavingsAmount(Amount estimateSavingsAmount) {
    this.estimateSavingsAmount = estimateSavingsAmount;
    return this;
  }

  /**
   * estimateSavingsAmount
   * @return estimateSavingsAmount
   */
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ESTIMATE_SAVINGS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getEstimateSavingsAmount() {
    return estimateSavingsAmount;
  }

  /**
   * estimateSavingsAmount
   *
   * @param estimateSavingsAmount
   */ 
  @JsonProperty(JSON_PROPERTY_ESTIMATE_SAVINGS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstimateSavingsAmount(Amount estimateSavingsAmount) {
    this.estimateSavingsAmount = estimateSavingsAmount;
  }

  /**
   * Return true if this Discount object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Discount discount = (Discount) o;
    return Objects.equals(this.discountTag, discount.discountTag) &&
        Objects.equals(this.discountName, discount.discountName) &&
        Objects.equals(this.estimateSavingsAmount, discount.estimateSavingsAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(discountTag, discountName, estimateSavingsAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Discount {\n");
    sb.append("    discountTag: ").append(toIndentedString(discountTag)).append("\n");
    sb.append("    discountName: ").append(toIndentedString(discountName)).append("\n");
    sb.append("    estimateSavingsAmount: ").append(toIndentedString(estimateSavingsAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

/**
   * Create an instance of Discount given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Discount
   * @throws JsonProcessingException if the JSON string is invalid with respect to Discount
   */
  public static Discount fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, Discount.class);
  }
/**
  * Convert an instance of Discount to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
