/*
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.consult;

//model

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.adyen.model.consult.Amount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * InterestFree
 */
@JsonPropertyOrder({
  InterestFree.JSON_PROPERTY_PROVIDER,
  InterestFree.JSON_PROPERTY_EXPIRE_TIME,
  InterestFree.JSON_PROPERTY_INSTALLMENT_FREE_NUMS,
  InterestFree.JSON_PROPERTY_MIN_PAYMENT_AMOUNT,
  InterestFree.JSON_PROPERTY_MAX_PAYMENT_AMOUNT,
  InterestFree.JSON_PROPERTY_FREE_PERCENTAGE
})
//pojo

public class InterestFree {
  public static final String JSON_PROPERTY_PROVIDER = "provider";
  private String provider;

  public static final String JSON_PROPERTY_EXPIRE_TIME = "expireTime";
  private LocalDate expireTime;

  public static final String JSON_PROPERTY_INSTALLMENT_FREE_NUMS = "installmentFreeNums";
  private Integer installmentFreeNums;

  public static final String JSON_PROPERTY_MIN_PAYMENT_AMOUNT = "minPaymentAmount";
  private Amount minPaymentAmount;

  public static final String JSON_PROPERTY_MAX_PAYMENT_AMOUNT = "maxPaymentAmount";
  private Amount maxPaymentAmount;

  public static final String JSON_PROPERTY_FREE_PERCENTAGE = "freePercentage";
  private Integer freePercentage;

  public InterestFree() { 
  }

  /**
   * Issuing banks or financial institutions that offer interest-free installment plans.
   *
   * @param provider
   * @return the current {@code InterestFree} instance, allowing for method chaining
   */
  public InterestFree provider(String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Issuing banks or financial institutions that offer interest-free installment plans.
   * @return provider
   */
  @ApiModelProperty(value = "Issuing banks or financial institutions that offer interest-free installment plans.")
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProvider() {
    return provider;
  }

  /**
   * Issuing banks or financial institutions that offer interest-free installment plans.
   *
   * @param provider
   */ 
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(String provider) {
    this.provider = provider;
  }

  /**
   * The promotion expiration time.
   *
   * @param expireTime
   * @return the current {@code InterestFree} instance, allowing for method chaining
   */
  public InterestFree expireTime(LocalDate expireTime) {
    this.expireTime = expireTime;
    return this;
  }

  /**
   * The promotion expiration time.
   * @return expireTime
   */
  @ApiModelProperty(value = "The promotion expiration time.")
  @JsonProperty(JSON_PROPERTY_EXPIRE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getExpireTime() {
    return expireTime;
  }

  /**
   * The promotion expiration time.
   *
   * @param expireTime
   */ 
  @JsonProperty(JSON_PROPERTY_EXPIRE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpireTime(LocalDate expireTime) {
    this.expireTime = expireTime;
  }

  /**
   * The number of interest-free installments.
   *
   * @param installmentFreeNums
   * @return the current {@code InterestFree} instance, allowing for method chaining
   */
  public InterestFree installmentFreeNums(Integer installmentFreeNums) {
    this.installmentFreeNums = installmentFreeNums;
    return this;
  }

  /**
   * The number of interest-free installments.
   * minimum: 2
   * @return installmentFreeNums
   */
  @ApiModelProperty(value = "The number of interest-free installments.")
  @JsonProperty(JSON_PROPERTY_INSTALLMENT_FREE_NUMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getInstallmentFreeNums() {
    return installmentFreeNums;
  }

  /**
   * The number of interest-free installments.
   *
   * @param installmentFreeNums
   */ 
  @JsonProperty(JSON_PROPERTY_INSTALLMENT_FREE_NUMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstallmentFreeNums(Integer installmentFreeNums) {
    this.installmentFreeNums = installmentFreeNums;
  }

  /**
   * minPaymentAmount
   *
   * @param minPaymentAmount
   * @return the current {@code InterestFree} instance, allowing for method chaining
   */
  public InterestFree minPaymentAmount(Amount minPaymentAmount) {
    this.minPaymentAmount = minPaymentAmount;
    return this;
  }

  /**
   * minPaymentAmount
   * @return minPaymentAmount
   */
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MIN_PAYMENT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getMinPaymentAmount() {
    return minPaymentAmount;
  }

  /**
   * minPaymentAmount
   *
   * @param minPaymentAmount
   */ 
  @JsonProperty(JSON_PROPERTY_MIN_PAYMENT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinPaymentAmount(Amount minPaymentAmount) {
    this.minPaymentAmount = minPaymentAmount;
  }

  /**
   * maxPaymentAmount
   *
   * @param maxPaymentAmount
   * @return the current {@code InterestFree} instance, allowing for method chaining
   */
  public InterestFree maxPaymentAmount(Amount maxPaymentAmount) {
    this.maxPaymentAmount = maxPaymentAmount;
    return this;
  }

  /**
   * maxPaymentAmount
   * @return maxPaymentAmount
   */
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAX_PAYMENT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getMaxPaymentAmount() {
    return maxPaymentAmount;
  }

  /**
   * maxPaymentAmount
   *
   * @param maxPaymentAmount
   */ 
  @JsonProperty(JSON_PROPERTY_MAX_PAYMENT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxPaymentAmount(Amount maxPaymentAmount) {
    this.maxPaymentAmount = maxPaymentAmount;
  }

  /**
   * The interest-free percentage. A value of 0 indicates no interest-free, 100% indicates the buyer is completely interest-free, while the value between 0-100% indicates partial interest-free.
   *
   * @param freePercentage
   * @return the current {@code InterestFree} instance, allowing for method chaining
   */
  public InterestFree freePercentage(Integer freePercentage) {
    this.freePercentage = freePercentage;
    return this;
  }

  /**
   * The interest-free percentage. A value of 0 indicates no interest-free, 100% indicates the buyer is completely interest-free, while the value between 0-100% indicates partial interest-free.
   * @return freePercentage
   */
  @ApiModelProperty(value = "The interest-free percentage. A value of 0 indicates no interest-free, 100% indicates the buyer is completely interest-free, while the value between 0-100% indicates partial interest-free.")
  @JsonProperty(JSON_PROPERTY_FREE_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFreePercentage() {
    return freePercentage;
  }

  /**
   * The interest-free percentage. A value of 0 indicates no interest-free, 100% indicates the buyer is completely interest-free, while the value between 0-100% indicates partial interest-free.
   *
   * @param freePercentage
   */ 
  @JsonProperty(JSON_PROPERTY_FREE_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFreePercentage(Integer freePercentage) {
    this.freePercentage = freePercentage;
  }

  /**
   * Return true if this InterestFree object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterestFree interestFree = (InterestFree) o;
    return Objects.equals(this.provider, interestFree.provider) &&
        Objects.equals(this.expireTime, interestFree.expireTime) &&
        Objects.equals(this.installmentFreeNums, interestFree.installmentFreeNums) &&
        Objects.equals(this.minPaymentAmount, interestFree.minPaymentAmount) &&
        Objects.equals(this.maxPaymentAmount, interestFree.maxPaymentAmount) &&
        Objects.equals(this.freePercentage, interestFree.freePercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, expireTime, installmentFreeNums, minPaymentAmount, maxPaymentAmount, freePercentage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterestFree {\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    expireTime: ").append(toIndentedString(expireTime)).append("\n");
    sb.append("    installmentFreeNums: ").append(toIndentedString(installmentFreeNums)).append("\n");
    sb.append("    minPaymentAmount: ").append(toIndentedString(minPaymentAmount)).append("\n");
    sb.append("    maxPaymentAmount: ").append(toIndentedString(maxPaymentAmount)).append("\n");
    sb.append("    freePercentage: ").append(toIndentedString(freePercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

/**
   * Create an instance of InterestFree given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InterestFree
   * @throws JsonProcessingException if the JSON string is invalid with respect to InterestFree
   */
  public static InterestFree fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, InterestFree.class);
  }
/**
  * Convert an instance of InterestFree to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
