/*
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.consult;

//model

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.adyen.model.consult.PaymentOption;
import com.adyen.model.consult.Result;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * PayConsultResponse
 */
@JsonPropertyOrder({
  PayConsultResponse.JSON_PROPERTY_RESULT,
  PayConsultResponse.JSON_PROPERTY_PAYMENT_OPTIONS
})
//pojo

public class PayConsultResponse {
  public static final String JSON_PROPERTY_RESULT = "result";
  private Result result;

  public static final String JSON_PROPERTY_PAYMENT_OPTIONS = "paymentOptions";
  private List<PaymentOption> paymentOptions = null;

  public PayConsultResponse() { 
  }

  /**
   * result
   *
   * @param result
   * @return the current {@code PayConsultResponse} instance, allowing for method chaining
   */
  public PayConsultResponse result(Result result) {
    this.result = result;
    return this;
  }

  /**
   * result
   * @return result
   */
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Result getResult() {
    return result;
  }

  /**
   * result
   *
   * @param result
   */ 
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(Result result) {
    this.result = result;
  }

  /**
   * The payment option list.
   *
   * @param paymentOptions
   * @return the current {@code PayConsultResponse} instance, allowing for method chaining
   */
  public PayConsultResponse paymentOptions(List<PaymentOption> paymentOptions) {
    this.paymentOptions = paymentOptions;
    return this;
  }

  public PayConsultResponse addPaymentOptionsItem(PaymentOption paymentOptionsItem) {
    if (this.paymentOptions == null) {
      this.paymentOptions = new ArrayList<>();
    }
    this.paymentOptions.add(paymentOptionsItem);
    return this;
  }

  /**
   * The payment option list.
   * @return paymentOptions
   */
  @ApiModelProperty(value = "The payment option list.")
  @JsonProperty(JSON_PROPERTY_PAYMENT_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<PaymentOption> getPaymentOptions() {
    return paymentOptions;
  }

  /**
   * The payment option list.
   *
   * @param paymentOptions
   */ 
  @JsonProperty(JSON_PROPERTY_PAYMENT_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentOptions(List<PaymentOption> paymentOptions) {
    this.paymentOptions = paymentOptions;
  }

  /**
   * Return true if this PayConsultResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayConsultResponse payConsultResponse = (PayConsultResponse) o;
    return Objects.equals(this.result, payConsultResponse.result) &&
        Objects.equals(this.paymentOptions, payConsultResponse.paymentOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, paymentOptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayConsultResponse {\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    paymentOptions: ").append(toIndentedString(paymentOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

/**
   * Create an instance of PayConsultResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PayConsultResponse
   * @throws JsonProcessingException if the JSON string is invalid with respect to PayConsultResponse
   */
  public static PayConsultResponse fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, PayConsultResponse.class);
  }
/**
  * Convert an instance of PayConsultResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
