/*
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.consult;

//model

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * PaymentAmount
 */
@JsonPropertyOrder({
  PaymentAmount.JSON_PROPERTY_CURRENCY,
  PaymentAmount.JSON_PROPERTY_VALUE
})
//pojo

public class PaymentAmount {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Double value;

  public PaymentAmount() { 
  }

  /**
   * The 3-letter currency code that follows the ISO 4217 standard.
   *
   * @param currency
   * @return the current {@code PaymentAmount} instance, allowing for method chaining
   */
  public PaymentAmount currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * The 3-letter currency code that follows the ISO 4217 standard.
   * @return currency
   */
  @ApiModelProperty(required = true, value = "The 3-letter currency code that follows the ISO 4217 standard.")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }

  /**
   * The 3-letter currency code that follows the ISO 4217 standard.
   *
   * @param currency
   */ 
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   * The amount of the payment.
   *
   * @param value
   * @return the current {@code PaymentAmount} instance, allowing for method chaining
   */
  public PaymentAmount value(Double value) {
    this.value = value;
    return this;
  }

  /**
   * The amount of the payment.
   * @return value
   */
  @ApiModelProperty(required = true, value = "The amount of the payment.")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getValue() {
    return value;
  }

  /**
   * The amount of the payment.
   *
   * @param value
   */ 
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(Double value) {
    this.value = value;
  }

  /**
   * Return true if this PaymentAmount object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAmount paymentAmount = (PaymentAmount) o;
    return Objects.equals(this.currency, paymentAmount.currency) &&
        Objects.equals(this.value, paymentAmount.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAmount {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

/**
   * Create an instance of PaymentAmount given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentAmount
   * @throws JsonProcessingException if the JSON string is invalid with respect to PaymentAmount
   */
  public static PaymentAmount fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, PaymentAmount.class);
  }
/**
  * Convert an instance of PaymentAmount to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
