/*
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.consult;

//model

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * PaymentFactor
 */
@JsonPropertyOrder({
  PaymentFactor.JSON_PROPERTY_PRESENTMENT_MODE
})
//pojo

public class PaymentFactor {
  /**
   * The presentation mode chosen by the merchant to display the payment methods on the cashier page. Valid values are:
   */
  public enum PresentmentModeEnum {
    TILE("TILE"),
    
    UNIFIED("UNIFIED");

    private String value;

    PresentmentModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PresentmentModeEnum fromValue(String value) {
      for (PresentmentModeEnum b : PresentmentModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PRESENTMENT_MODE = "presentmentMode";
  private PresentmentModeEnum presentmentMode;

  public PaymentFactor() { 
  }

  /**
   * The presentation mode chosen by the merchant to display the payment methods on the cashier page. Valid values are:
   *
   * @param presentmentMode
   * @return the current {@code PaymentFactor} instance, allowing for method chaining
   */
  public PaymentFactor presentmentMode(PresentmentModeEnum presentmentMode) {
    this.presentmentMode = presentmentMode;
    return this;
  }

  /**
   * The presentation mode chosen by the merchant to display the payment methods on the cashier page. Valid values are:
   * @return presentmentMode
   */
  @ApiModelProperty(value = "The presentation mode chosen by the merchant to display the payment methods on the cashier page. Valid values are:")
  @JsonProperty(JSON_PROPERTY_PRESENTMENT_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PresentmentModeEnum getPresentmentMode() {
    return presentmentMode;
  }

  /**
   * The presentation mode chosen by the merchant to display the payment methods on the cashier page. Valid values are:
   *
   * @param presentmentMode
   */ 
  @JsonProperty(JSON_PROPERTY_PRESENTMENT_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPresentmentMode(PresentmentModeEnum presentmentMode) {
    this.presentmentMode = presentmentMode;
  }

  /**
   * Return true if this PaymentFactor object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentFactor paymentFactor = (PaymentFactor) o;
    return Objects.equals(this.presentmentMode, paymentFactor.presentmentMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(presentmentMode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentFactor {\n");
    sb.append("    presentmentMode: ").append(toIndentedString(presentmentMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

/**
   * Create an instance of PaymentFactor given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentFactor
   * @throws JsonProcessingException if the JSON string is invalid with respect to PaymentFactor
   */
  public static PaymentFactor fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, PaymentFactor.class);
  }
/**
  * Convert an instance of PaymentFactor to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
