/*
 * Payment API
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.service.consult;

//api
import com.adyen.Client;
import com.adyen.Service;
import com.adyen.constants.ApiConstants;
import com.adyen.model.consult.PayConsultRequest;
import com.adyen.model.consult.PayConsultResponse;
import com.adyen.model.RequestOptions;
import com.adyen.service.exception.ApiException;
import com.adyen.service.resource.Resource;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class DefaultApi extends Service {

    public static final String API_VERSION = "1";

    protected String baseURL;

    /**
    * default constructor in {@link com.adyen.service.consult package}.
    * @param client {@link Client } (required)
    */
    public DefaultApi(Client client) {
        super(client);
        this.baseURL = createBaseURL("https://open-sea-global.alipay.com/ams/api/v1/payments");
    }

    /**
    * default constructor in {@link com.adyen.service.consult package}.
    * Please use this constructor only if you would like to pass along your own url for routing or testing purposes. The latest API version is defined in this class as a constant.
    * @param client {@link Client } (required)
    * @param baseURL {@link String } (required)
    */
    public DefaultApi(Client client, String baseURL) {
        super(client);
        this.baseURL = baseURL;
    }

    /**
    * consult payment methods
    *
    * @param payConsultRequest {@link PayConsultRequest }  (required)
    * @return {@link PayConsultResponse }
    * @throws ApiException if fails to make API call
    */
    public PayConsultResponse consultPayment(PayConsultRequest payConsultRequest) throws ApiException, IOException {
        return consultPayment(payConsultRequest, null);
    }

    /**
    * consult payment methods
    *
    * @param payConsultRequest {@link PayConsultRequest }  (required)
    * @param requestOptions {@link RequestOptions } Object to store additional data such as idempotency-keys (optional)
    * @return {@link PayConsultResponse }
    * @throws ApiException if fails to make API call
    */
    public PayConsultResponse consultPayment(PayConsultRequest payConsultRequest, RequestOptions requestOptions) throws ApiException, IOException {

        String requestBody = payConsultRequest.toJson();
        Resource resource = new Resource(this, this.baseURL + "/consult", null);
        String jsonResult = resource.request(requestBody, requestOptions, ApiConstants.HttpMethod.POST, null);
        return PayConsultResponse.fromJson(jsonResult);
    }
}
